apiVersion: apps/v1
kind: Deployment
metadata:
  name: slogan-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slogan-generator
  template:
    metadata:
      labels:
        app: slogan-generator
    spec:
      containers:
      - name: slogan-generator
        image: greystone/slogan-generator:0.1.16
        ports:
        - containerPort: 9090
        command: ["java"]
        args: ["-jar", "/deployments/quarkus-run.jar"]
