apiVersion: v1
kind: Service
metadata:
  name: slogan-generator
spec:
  selector:
    app: slogan-generator
  ports:
  - port: 31415
    targetPort: 8080  # Should match the containerPort in the Deployment
    nodePort: 31415
  type: NodePort
